development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://lxryhyfketurcy:f1becee8c2092db32afff44b5ea2b1787e1d4890978fd0ad2a49fef3b85b31b0@ec2-54-228-255-234.eu-west-1.compute.amazonaws.com:5432/de0gjhv5o52pen
